"""Version the offline app shell. Run after changing public/ or content.json."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'public'


def build():
    paths = sorted(p for p in ROOT.rglob('*') if p.is_file() and p.name not in {'service-worker.js','_headers'})
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.relative_to(ROOT).as_posix().encode())
        digest.update(path.read_bytes())
    revision = digest.hexdigest()[:16]
    assets = ['./'] + ['./' + p.relative_to(ROOT).as_posix() for p in paths]
    worker = '''// Generated by tools/build_release.py. Every release is an atomic offline cache.
const CACHE = 'wordboat-static-REVISION';
const FILES = ASSETS;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)));
});
self.addEventListener('message', event => {
  if(event.data === 'ACTIVATE_UPDATE') self.skipWaiting();
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('wordboat-static-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request=event.request, url=new URL(request.url);
  if(request.method!=='GET'||url.origin!==self.location.origin) return;
  const base=new URL('./',self.location.href);
  if(!url.pathname.startsWith(base.pathname)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    if(request.mode==='navigate') return (await cache.match(new URL('index.html',base))) || fetch(request);
    return (await cache.match(request,{ignoreSearch:true})) || fetch(request);
  }));
'''.replace('REVISION', revision).replace('ASSETS', json.dumps(assets))
    (ROOT/'service-worker.js').write_text(worker, encoding='utf-8')
    print(f'Offline release {revision}, {len(assets)} assets')


if __name__ == '__main__':
    build()
